import fs from "fs/promises";
import path from "path";
import { createDebugLogger } from '../utils/debug.js';
import { atomicWrite } from '../utils/fileUtils.js';
import { getConfig, CONTEXT_SESSION_DIR } from '../config.js';
import { extractPersistentPatterns, extractSessionContent, extractBugs, findPatterns } from './contentExtractor.js';

const logger = createDebugLogger('intelligence');

/**
 * Check if session is high priority and should be preserved
 * @param {Object} sessionData - Session object with priority field
 * @returns {boolean}
 */
export function isHighPriority(sessionData) {
  return sessionData.priority === 'high';
}

export async function initializeIntelligenceLearning(baseDir) {
  const ctxDir = path.join(baseDir, CONTEXT_SESSION_DIR);
  const filePath = path.join(ctxDir, 'intelligence-learning.md');
  
  try {
    try {
      await fs.access(filePath);
      logger(`[Intelligence] File already exists, skipping initialization: ${filePath}`);
      return filePath;
    } catch {
    }
    
    const projectName = path.basename(baseDir);
    const timestamp = new Date().toISOString();
    
    const content = `# Intelligence Learning - ${projectName}

**Last Updated:** ${timestamp}

> This file auto-populates as sessions are analyzed. See below for current state.

---

## Current Patterns

### Pinned Patterns
- [Auto-populated from cross-session analysis]

### Recent Sessions
- [Auto-populated from recent sessions]

### Bug Patterns
- [Auto-populated from session analysis]

---

*Auto-generated by OpenCode Context Plugin*
`;
    
    await fs.mkdir(ctxDir, { recursive: true });
    await atomicWrite(filePath, content);
    logger(`[Intelligence] Initialized intelligence learning file: ${filePath}`);
    console.log(`[context-plugin] Intelligence learning file initialized`);
    
    return filePath;
  } catch (error) {
    logger(`[Intelligence] Error initializing learning file: ${error.message}`);
    console.error(`[context-plugin] Failed to initialize intelligence learning: ${error.message}`);
    throw error;
  }
}

/**
 * Preserve persistent patterns across intelligence updates
 * Extracts patterns from existing file, pins those with sessionCount >= 3
 * Merges new patterns with pinned ones
 * 
 * @param {string} existingContent - Current intelligence-learning.md content
 * @param {Array} newPatterns - New patterns from findPatterns()
 * @returns {Object} { pinnedContent, recentContent }
 */
export function preservePersistentPatterns(existingContent, newPatterns) {
  // Extract existing persistent patterns
  const existingPatterns = extractPersistentPatterns(existingContent);
  
  // Separate pinned (sessionCount >= 2) from recent
  const pinnedPatterns = existingPatterns.filter(p => p.pinned);
  const recentPatterns = newPatterns || [];
  
  // Merge: new patterns may increment session counts on existing pinned patterns
  const mergedPinned = mergePatterns(pinnedPatterns, recentPatterns);
  
  return {
    pinnedContent: formatPinnedPatterns(mergedPinned),
    recentContent: formatRecentPatterns(recentPatterns)
  };
}

function mergePatterns(pinned, newPatterns) {
  // For each new pattern, check if it matches an existing pinned pattern
  // If so, increment session count; otherwise keep pinned as-is
  const result = [...pinned];
  
  for (const newPat of newPatterns) {
    const matchIdx = result.findIndex(p => 
      p.pattern.toLowerCase() === newPat.pattern.toLowerCase()
    );
    if (matchIdx >= 0) {
      // Update existing pinned pattern with new session
      result[matchIdx].sessions.push(...newPat.sessions);
      result[matchIdx].sessionCount = result[matchIdx].sessions.length;
      result[matchIdx].lastSeen = new Date().toISOString().split('T')[0];
      result[matchIdx].pinned = result[matchIdx].sessionCount >= 2;
    }
    // New patterns that aren't pinned yet go to recent, not pinned
  }
  
  return result;
}

function formatPinnedPatterns(patterns) {
  if (!patterns || patterns.length === 0) {
    return 'No pinned patterns yet (appear in 2+ sessions to pin)\n';
  }
  
  // Group by type
  const byType = {
    goal_theme: patterns.filter(p => p.type === 'goal_theme'),
    bug_pattern: patterns.filter(p => p.type === 'bug_pattern'),
    file_pattern: patterns.filter(p => p.type === 'file_pattern'),
    general: patterns.filter(p => !['goal_theme', 'bug_pattern', 'file_pattern'].includes(p.type))
  };
  
  let content = '';
  
  if (byType.goal_theme.length > 0) {
    content += '### Pinned Goal Themes\n';
    for (const p of byType.goal_theme) {
      content += `- ${p.pattern} (Sessions: ${p.sessionCount}, Last: ${p.lastSeen})\n`;
    }
    content += '\n';
  }
  
  if (byType.bug_pattern.length > 0) {
    content += '### Pinned Bug Patterns\n';
    for (const p of byType.bug_pattern) {
      content += `- ${p.pattern} (Sessions: ${p.sessionCount}, Last: ${p.lastSeen})\n`;
    }
    content += '\n';
  }
  
  if (byType.file_pattern.length > 0) {
    content += '### Pinned File Patterns\n';
    for (const p of byType.file_pattern) {
      content += `- ${p.pattern} (Sessions: ${p.sessionCount}, Last: ${p.lastSeen})\n`;
    }
    content += '\n';
  }
  
  if (byType.general.length > 0) {
    content += '### Other Pinned Patterns\n';
    for (const p of byType.general) {
      content += `- ${p.pattern} (Sessions: ${p.sessionCount}, Last: ${p.lastSeen})\n`;
    }
    content += '\n';
  }
  
  return content;
}

function formatRecentPatterns(patterns) {
  if (!patterns || patterns.length === 0) {
    return 'No recent patterns\n';
  }

  let content = '';
  for (const p of patterns.slice(0, 10)) { // Limit to top 10 recent
    content += `- ${p.pattern} (Sessions: ${p.sessionCount})\n`;
  }

  return content;
}

/**
 * Count bugs by category from session data
 * @param {Array} sessions - Array of session objects with bugs
 * @returns {Object} { categoryCounts: {name: count}, totalBugs: number }
 */
function countBugsByCategory(sessions) {
  const categoryCounts = {};
  let totalBugs = 0;

  for (const session of sessions) {
    if (!session.bugs || !Array.isArray(session.bugs)) continue;
    for (const bug of session.bugs) {
      totalBugs++;
      const symptom = (bug.symptom || '').toLowerCase();

      let category = 'other';
      if (symptom.includes('parser') || symptom.includes('parse')) category = 'parser';
      else if (symptom.includes('config') || symptom.includes('setting')) category = 'config';
      else if (symptom.includes('file') || symptom.includes('path') || symptom.includes('dir')) category = 'file-system';
      else if (symptom.includes('memory') || symptom.includes('leak')) category = 'memory';
      else if (symptom.includes('sync') || symptom.includes('remote')) category = 'sync';
      else if (symptom.includes('token') || symptom.includes('limit')) category = 'token-limit';
      else if (symptom.includes('debounce') || symptom.includes('timing')) category = 'timing';
      else if (symptom.includes('inject') || symptom.includes('context')) category = 'context-injection';

      categoryCounts[category] = (categoryCounts[category] || 0) + 1;
    }
  }

  return { categoryCounts, totalBugs };
}

/**
 * Find top N goal patterns from sessions
 * @param {Array} sessions - Array of session objects
 * @param {number} topN - Number of top patterns to return
 * @returns {Array} Array of {pattern, count, examples}
 */
function findTopGoalPatterns(sessions, topN = 3) {
  const goalMap = new Map();

  for (const session of sessions) {
    const goal = session.goal || '';
    if (!goal || goal.length < 10) continue;

    const normalized = goal.toLowerCase().replace(/[^a-z0-9\s]/g, '').trim();
    const words = normalized.split(/\s+/).filter(w => w.length > 3);
    const key = words.slice(0, 5).join(' ');

    if (!goalMap.has(key)) {
      goalMap.set(key, { pattern: goal.slice(0, 60), count: 0, examples: [] });
    }
    const entry = goalMap.get(key);
    entry.count++;
    if (entry.examples.length < 2) {
      entry.examples.push(goal.slice(0, 80));
    }
  }

  return Array.from(goalMap.values())
    .sort((a, b) => b.count - a.count)
    .slice(0, topN);
}

/**
 * Calculate context quality percentage
 * Checks for Goal + Accomplished + (Discoveries OR Relevant Files)
 * @param {Object} extracted - Extracted session content
 * @returns {number} Quality percentage 0-100
 */
function calculateContextQuality(extracted) {
  let score = 0;
  const maxScore = 3;

  if (extracted.goal && extracted.goal.length > 10) score++;
  if (extracted.accomplished && extracted.accomplished.length > 10) score++;
  if ((extracted.discoveries && extracted.discoveries.length > 10) ||
      (extracted.relevantFiles && extracted.relevantFiles.length > 0)) score++;

  return Math.round((score / maxScore) * 100);
}

/**
 * Generate real intelligence analysis from session data
 * @param {Array} sessions - Array of session summaries
 * @returns {Object} Analysis results
 */
export function generateIntelligenceLearning(sessions) {
  if (!sessions || sessions.length === 0) {
    return {
      bugCounts: {},
      totalBugs: 0,
      topGoalPatterns: [],
      contextQualityPercent: 0,
      recommendations: []
    };
  }

  const bugData = countBugsByCategory(sessions);
  const topGoals = findTopGoalPatterns(sessions, 3);

  let qualitySum = 0;
  let qualityCount = 0;
  for (const session of sessions) {
    const extracted = extractSessionContent(session.content || '');
    qualitySum += calculateContextQuality(extracted);
    qualityCount++;
  }
  const avgQuality = qualityCount > 0 ? Math.round(qualitySum / qualityCount) : 0;

  const recommendations = [];
  if (bugData.totalBugs > 0) {
    recommendations.push(`Focus on ${Object.keys(bugData.categoryCounts)[0]} bugs (${bugData.totalBugs} total found)`);
  }
  if (avgQuality < 70) {
    recommendations.push('Improve session content quality - add ## Goal, ## Accomplished, and ## Discoveries sections');
  }
  if (topGoals.length > 0) {
    recommendations.push(`Top goal pattern: "${topGoals[0].pattern}" seen in ${topGoals[0].count} sessions`);
  }

  return {
    bugCounts: bugData.categoryCounts,
    totalBugs: bugData.totalBugs,
    topGoalPatterns: topGoals,
    contextQualityPercent: avgQuality,
    recommendations
  };
}
