import fs from "fs/promises";
import path from "path";
import { createDebugLogger } from '../utils/debug.js';
import { atomicWrite } from '../utils/fileUtils.js';
import { extractSessionContent, extractBugs } from './contentExtractor.js';

const logger = createDebugLogger('intelligence');

// Constants
const CONTEXT_SESSION_DIR = '.opencode/context-session';

// Queue-based serialization for intelligence learning updates
let learningWriteQueue = Promise.resolve();

/**
 * Initialize intelligence learning file with template
 */
export async function initializeIntelligenceLearning(baseDir) {
  const ctxDir = path.join(baseDir, CONTEXT_SESSION_DIR);
  const filePath = path.join(ctxDir, 'intelligence-learning.md');
  
  try {
    // Check if file already exists (don't overwrite)
    try {
      await fs.access(filePath);
      logger(`[Intelligence] File already exists, skipping initialization: ${filePath}`);
      return filePath;
    } catch {
      // File doesn't exist, proceed with creation
    }
    
    // Get project name from directory
    const projectName = path.basename(baseDir);
    const timestamp = new Date().toISOString();
    
    // Create template content
    let content = `# Intelligence Learning - ${projectName}\n\n`;
    content += `## Last Updated\n`;
    content += `- **Timestamp:** ${timestamp}\n`;
    content += `- **Sessions Analyzed:** 0\n`;
    content += `- **Last Session Type:** none\n\n`;
    
    content += `## Project Structure Decisions\n\n`;
    content += `### Folder Hierarchy\n`;
    content += `- **Why:** Temporal organization enables quick navigation by date\n`;
    content += `- **Structure:** YYYY/MM/WW/DD with summaries at each level\n`;
    content += `- **Tradeoff:** More directories vs. flat structure with search\n\n`;
    
    content += `### Naming Conventions\n`;
    content += `- **exit-***: Session end (replaced "saida-" for i18n)\n`;
    content += `- **compact-***: Manual or auto compaction\n`;
    content += `- **summary.md**: Auto-generated summaries\n\n`;
    
    content += `## Architectural Decisions\n\n`;
    content += `### Hook Selection\n`;
    content += `- **session.compacted**: For manual/auto compaction\n`;
    content += `- **session.idle**: For automatic session end detection\n`;
    content += `- **session.deleted**: For explicit session deletion\n`;
    content += `- **Pre-exit trigger**: Custom hook before session ends\n\n`;
    
    content += `### Event Handling Pattern\n`;
    content += `- Use closure to access \`client\` object (not from event handler params)\n`;
    content += `- Queue-based write serialization (no file locking needed)\n`;
    content += `- Atomic writes via temp-file-rename pattern\n\n`;
    
    content += `## Bug Fix Guidance\n\n`;
    content += `### Common Issue: "client is undefined"\n`;
    content += `**Symptom:** Error "undefined is not an object (evaluating 'client.sessions.get")\n`;
    content += `**Cause:** Event handler doesn't receive client parameter\n`;
    content += `**Fix:** Use client from closure (outer plugin function scope)\n\n`;
    
    content += `### Common Issue: File corruption on crash\n`;
    content += `**Symptom:** Truncated or malformed summary files\n`;
    content += `**Cause:** Synchronous writes interrupted mid-operation\n`;
    content += `**Fix:** Use atomic write pattern (temp file + rename)\n\n`;
    
    content += `## Session Patterns\n\n`;
    content += `### Typical Session Duration\n`;
    content += `- [Auto-populated from session analysis]\n\n`;
    
    content += `### Common Commands\n`;
    content += `- [Auto-populated from session analysis]\n\n`;
    
    content += `## Key Learnings from Latest Sessions\n\n`;
    content += `[Appended on each trigger execution]\n\n`;
    
    content += `---\n`;
    content += `*Auto-generated by OpenCode Context Plugin*\n`;
    
    // Ensure directory exists
    await fs.mkdir(ctxDir, { recursive: true });
    
    // Atomic write
    await atomicWrite(filePath, content);
    logger(`[Intelligence] Initialized intelligence learning file: ${filePath}`);
    console.log(`[context-plugin] Intelligence learning file initialized`);
    
    return filePath;
  } catch (error) {
    logger(`[Intelligence] Error initializing learning file: ${error.message}`);
    console.error(`[context-plugin] Failed to initialize intelligence learning: ${error.message}`);
    throw error;
  }
}

/**
 * Update intelligence learning file with new session info
 * Uses queue-based serialization to prevent write conflicts
 */
export async function updateIntelligenceLearning(baseDir, sessionInfo) {
  // Queue-based serialization to prevent concurrent write conflicts
  learningWriteQueue = learningWriteQueue.then(async () => {
    try {
      // Handle null/undefined session info gracefully
      if (!sessionInfo || !sessionInfo.type) {
        logger(`[Intelligence] Invalid session info, skipping update`);
        return;
      }
      
      const ctxDir = path.join(baseDir, CONTEXT_SESSION_DIR);
      const filePath = path.join(ctxDir, 'intelligence-learning.md');
      
      // Read existing content
      let content;
      try {
        content = await fs.readFile(filePath, 'utf-8');
      } catch (error) {
        logger(`[Intelligence] Cannot read learning file, skipping update: ${error.message}`);
        return;
      }
      
      // Update Last Updated section
      const lines = content.split('\n');
      const updatedLines = [];
      let inLastUpdatedSection = false;
      let sessionsAnalyzed = 0;
      
      for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        
        // Track Last Updated section
        if (line.startsWith('## Last Updated')) {
          inLastUpdatedSection = true;
          updatedLines.push(line);
          continue;
        }
        
        if (inLastUpdatedSection && line.startsWith('## ')) {
          inLastUpdatedSection = false;
        }
        
        // Update timestamp
        if (inLastUpdatedSection && line.includes('**Timestamp:**')) {
          updatedLines.push(`- **Timestamp:** ${sessionInfo.timestamp || new Date().toISOString()}`);
          continue;
        }
        
        // Update session count
        if (inLastUpdatedSection && line.includes('**Sessions Analyzed:**')) {
          const match = line.match(/Sessions Analyzed:\s*(\d+)/);
          sessionsAnalyzed = match ? parseInt(match[1], 10) + 1 : 1;
          updatedLines.push(`- **Sessions Analyzed:** ${sessionsAnalyzed}`);
          continue;
        }
        
        // Update session type
        if (inLastUpdatedSection && line.includes('**Last Session Type:**')) {
          updatedLines.push(`- **Last Session Type:** ${sessionInfo.type}`);
          continue;
        }
        
        updatedLines.push(line);
      }
      
      content = updatedLines.join('\n');
      
      // Extract structured content if session content is available
      let extracted = { goal: null, accomplished: null, discoveries: null, relevantFiles: [], firstUserMessage: null };
      let bugs = [];
      
      if (sessionInfo.content) {
        // Use contentExtractor functions if content is provided
        extracted = extractSessionContent(sessionInfo.content);
        bugs = extractBugs(sessionInfo.content);
      } else if (sessionInfo.filename) {
        // Try to read session file if filename is provided
        try {
          const sessionPath = path.join(ctxDir, '..', '..', sessionInfo.filename);
          const sessionContent = await fs.readFile(sessionPath, 'utf-8');
          extracted = extractSessionContent(sessionContent);
          bugs = extractBugs(sessionContent);
        } catch (error) {
          logger(`[Intelligence] Could not read session file: ${error.message}`);
        }
      }
      
      // Deduplicate: Check if this session already exists
      if (sessionInfo.sessionId && content.includes(sessionInfo.sessionId)) {
        logger(`[Intelligence] Session ${sessionInfo.sessionId} already recorded, skipping duplicate`);
        return;
      }
      
      // Build Key Learnings entry following template format
      const templateSections = [];
      
      if (extracted.goal) {
        templateSections.push(`## Goal\n${extracted.goal}`);
      }
      
      templateSections.push(`## Instructions\n${sessionInfo.type === 'exit' ? 'Session ended' : 'Session compacted'}`);
      
      if (extracted.discoveries) {
        templateSections.push(`## Discoveries\n${extracted.discoveries}`);
      }
      
      if (extracted.accomplished) {
        templateSections.push(`## Accomplished\n${extracted.accomplished}`);
      } else if (sessionInfo.messageCount) {
        templateSections.push(`## Accomplished\n${sessionInfo.messageCount} messages processed`);
      }
      
      if (extracted.relevantFiles.length > 0) {
        const filesList = extracted.relevantFiles.map(f => `- ${f}`).join('\n');
        templateSections.push(`## Relevant files / directories\n${filesList}`);
      }
      
      // Add bug tracking if bugs with solutions were found
      if (bugs.length > 0) {
        const bugsSection = bugs.map(bug => {
          let bugEntry = `### Bug: ${bug.symptom}\n`;
          if (bug.cause) bugEntry += `**Cause:** ${bug.cause}\n`;
          if (bug.solution) bugEntry += `**Solution:** ${bug.solution}\n`;
          if (bug.prevention) bugEntry += `**Prevention:** ${bug.prevention}\n`;
          return bugEntry;
        }).join('\n');
        templateSections.push(`\n${bugsSection}`);
      }
      
      // Append to Key Learnings section
      const learningsMarker = '## Key Learnings from Latest Sessions';
      const learningsIndex = content.indexOf(learningsMarker);
      
      if (learningsIndex === -1) {
        logger(`[Intelligence] Key Learnings section not found, appending at end`);
        // Append before the footer
        const footerIndex = content.indexOf('---\n*Auto-generated');
        if (footerIndex !== -1) {
          let newEntry = `### Session ${sessionsAnalyzed} - ${sessionInfo.type.toUpperCase()}\n`;
          newEntry += `- **Date:** ${sessionInfo.timestamp || new Date().toISOString()}\n`;
          newEntry += `- **Session ID:** ${sessionInfo.sessionId || 'unknown'}\n\n`;
          newEntry += templateSections.join('\n\n');
          newEntry += '\n\n';
          
          content = content.slice(0, footerIndex) + newEntry + content.slice(footerIndex);
        }
      } else {
        // Find the end of the Key Learnings section (before footer)
        const sectionStart = learningsIndex + learningsMarker.length;
        const footerIndex = content.indexOf('---\n*Auto-generated', sectionStart);
        const insertPosition = footerIndex !== -1 ? footerIndex : content.length;
        
        let sectionContent = content.slice(sectionStart, insertPosition);
        const entries = sectionContent.split(/(?=### Session \d+)/).filter(s => s.trim().length > 0);
        
        // Limit to last 19 entries (adding 1 new = 20 total)
        if (entries.length >= 20) {
          entries.shift(); // Remove oldest
        }
        
        // Build new entry with template format
        let newEntry = `### Session ${sessionsAnalyzed} - ${sessionInfo.type.toUpperCase()}\n`;
        newEntry += `- **Date:** ${sessionInfo.timestamp || new Date().toISOString()}\n`;
        newEntry += `- **Session ID:** ${sessionInfo.sessionId || 'unknown'}\n\n`;
        newEntry += templateSections.join('\n\n');
        newEntry += '\n\n';
        
        entries.push(newEntry);
        
        // Rebuild section - join with \n### Session and prepend the marker
        const updatedSection = learningsMarker + '\n' + entries.join('\n### Session');
        content = content.slice(0, learningsIndex) + updatedSection + content.slice(insertPosition);
      }
      
      // Atomic write
      await atomicWrite(filePath, content);
      logger(`[Intelligence] Updated learning file: ${filePath}`);
    } catch (error) {
      logger(`[Intelligence] Error updating learning file: ${error.message}`);
      console.error(`[context-plugin] Intelligence learning update failed: ${error.message}`);
      // Don't throw - fail gracefully to not break session saving
    }
  });
  
  await learningWriteQueue;
}
