import fs from "fs/promises";
import path from "path";
import { createDebugLogger } from '../utils/debug.js';
import { atomicWrite } from '../utils/fileUtils.js';
import { getConfig } from '../config.js';

const logger = createDebugLogger('intelligence');

const CONTEXT_SESSION_DIR = '.opencode/context-session';

/**
 * Check if session is high priority and should be preserved
 * @param {Object} sessionData - Session object with priority field
 * @returns {boolean}
 */
export function isHighPriority(sessionData) {
  return sessionData.priority === 'high';
}

export async function initializeIntelligenceLearning(baseDir) {
  const ctxDir = path.join(baseDir, CONTEXT_SESSION_DIR);
  const filePath = path.join(ctxDir, 'intelligence-learning.md');
  
  try {
    // Check if file already exists (don't overwrite)
    try {
      await fs.access(filePath);
      logger(`[Intelligence] File already exists, skipping initialization: ${filePath}`);
      return filePath;
    } catch {
      // File doesn't exist, proceed with creation
    }
    
    // Get project name from directory
    const projectName = path.basename(baseDir);
    const timestamp = new Date().toISOString();
    
    // Create template content
    let content = `# Intelligence Learning - ${projectName}\n\n`;
    content += `## Last Updated\n`;
    content += `- **Timestamp:** ${timestamp}\n`;
    content += `- **Sessions Analyzed:** 0\n`;
    content += `- **Last Session Type:** none\n\n`;
    
    content += `## Project Structure Decisions\n\n`;
    content += `### Folder Hierarchy\n`;
    content += `- **Why:** Temporal organization enables quick navigation by date\n`;
    content += `- **Structure:** YYYY/MM/WW/DD with summaries at each level\n`;
    content += `- **Tradeoff:** More directories vs. flat structure with search\n\n`;
    
    content += `### Naming Conventions\n`;
    content += `- **exit-***: Session end (replaced "saida-" for i18n)\n`;
    content += `- **compact-***: Manual or auto compaction\n`;
    content += `- **summary.md**: Auto-generated summaries\n\n`;
    
    content += `## Architectural Decisions\n\n`;
    content += `### Hook Selection\n`;
    content += `- **session.compacted**: For manual/auto compaction\n`;
    content += `- **session.idle**: For automatic session end detection\n`;
    content += `- **session.deleted**: For explicit session deletion\n`;
    content += `- **Pre-exit trigger**: Custom hook before session ends\n\n`;
    
    content += `### Event Handling Pattern\n`;
    content += `- Use closure to access \`client\` object (not from event handler params)\n`;
    content += `- Queue-based write serialization (no file locking needed)\n`;
    content += `- Atomic writes via temp-file-rename pattern\n\n`;
    
    content += `## Bug Fix Guidance\n\n`;
    content += `### Common Issue: "client is undefined"\n`;
    content += `**Symptom:** Error "undefined is not an object (evaluating 'client.sessions.get")\n`;
    content += `**Cause:** Event handler doesn't receive client parameter\n`;
    content += `**Fix:** Use client from closure (outer plugin function scope)\n\n`;
    
    content += `### Common Issue: File corruption on crash\n`;
    content += `**Symptom:** Truncated or malformed summary files\n`;
    content += `**Cause:** Synchronous writes interrupted mid-operation\n`;
    content += `**Fix:** Use atomic write pattern (temp file + rename)\n\n`;
    
    content += `## Session Patterns\n\n`;
    content += `### Typical Session Duration\n`;
    content += `- [Auto-populated from session analysis]\n\n`;
    
    content += `### Common Commands\n`;
    content += `- [Auto-populated from session analysis]\n\n`;
    
    content += `### Recurring Themes\n`;
    content += `- [Auto-populated from cross-session analysis]\n\n`;
    
    content += `### Related Files\n`;
    content += `- [Auto-populated from cross-session analysis]\n\n`;
    
    content += `### Bug-Prone Areas\n`;
    content += `- [Auto-populated from cross-session analysis]\n\n`;

    content += `## High-Priority Session Preservation\n\n`;
    content += `Sessions marked as HIGH priority are preserved indefinitely:\n`;
    content += `- [Auto-populated: list of high-priority session IDs and their key learnings]\n\n`;

    content += `## Remote Sync Status\n\n`;
    content += `[Auto-populated when remote sync is configured]\n\n`;
    
    content += `## Key Learnings from Latest Sessions\n\n`;
    content += `[Appended on each trigger execution]\n\n`;
    
    content += `---\n`;
    content += `*Auto-generated by OpenCode Context Plugin*\n`;
    
    // Ensure directory exists
    await fs.mkdir(ctxDir, { recursive: true });
    
    // Atomic write
    await atomicWrite(filePath, content);
    logger(`[Intelligence] Initialized intelligence learning file: ${filePath}`);
    console.log(`[context-plugin] Intelligence learning file initialized`);
    
    return filePath;
  } catch (error) {
    logger(`[Intelligence] Error initializing learning file: ${error.message}`);
    console.error(`[context-plugin] Failed to initialize intelligence learning: ${error.message}`);
    throw error;
  }
}
