/**
 * Intelligence Module Tests
 */

import { jest, describe, it, expect, beforeEach, afterEach } from '@jest/globals';
import fs from 'fs/promises';
import os from 'os';
import path from 'path';

describe('Intelligence Module', () => {
  let tempDir;
  let ctxDir;

  beforeEach(async () => {
    jest.clearAllMocks();
    jest.useFakeTimers();
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'intelligence-test-'));
    ctxDir = path.join(tempDir, '.opencode', 'context-session');
    await fs.mkdir(ctxDir, { recursive: true });
  });

  afterEach(async () => {
    jest.useRealTimers();
    try {
      await fs.rm(tempDir, { recursive: true });
    } catch {}
  });

  describe('initializeIntelligenceLearning(baseDir)', () => {
    it('should create intelligence-learning.md with template content', async () => {
      const intelligence = await import('../src/modules/intelligence.js');

      await intelligence.initializeIntelligenceLearning(tempDir);

      const filePath = path.join(ctxDir, 'intelligence-learning.md');
      const content = await fs.readFile(filePath, 'utf-8');

      expect(content).toContain('Intelligence Learning');
      expect(content).toContain('Last Updated');
      expect(content).toContain('Key Learnings from Latest Sessions');
      expect(content).toContain('Auto-generated by OpenCode Context Plugin');
    });

    it('should skip if file already exists', async () => {
      const intelligence = await import('../src/modules/intelligence.js');

      // Create existing file
      await fs.writeFile(path.join(ctxDir, 'intelligence-learning.md'), '# Existing content\n');

      // Should not overwrite
      await intelligence.initializeIntelligenceLearning(tempDir);

      const content = await fs.readFile(path.join(ctxDir, 'intelligence-learning.md'), 'utf-8');
      expect(content).toBe('# Existing content\n');
    });

    it('should return the file path', async () => {
      const intelligence = await import('../src/modules/intelligence.js');

      const result = await intelligence.initializeIntelligenceLearning(tempDir);

      expect(result).toContain('intelligence-learning.md');
    });
  });

  describe('updateIntelligenceLearning(baseDir, sessionInfo)', () => {
    it('should update Sessions Analyzed count', async () => {
      const intelligence = await import('../src/modules/intelligence.js');

      // First initialize
      await intelligence.initializeIntelligenceLearning(tempDir);

      // Now update with session info
      const sessionInfo = {
        type: 'compact',
        filename: 'compact-2026-04-21T10-30-00.md',
        timestamp: '2026-04-21T10:30:00Z',
        sessionId: 'session-123',
        messageCount: 5
      };

      // Queue the update
      intelligence.updateIntelligenceLearning(tempDir, sessionInfo);

      // Advance timers to let queue process
      jest.advanceTimersByTime(100);
      await Promise.resolve();

      const content = await fs.readFile(path.join(ctxDir, 'intelligence-learning.md'), 'utf-8');

      // Sessions Analyzed should be updated
      expect(content).toContain('Sessions Analyzed:');
      expect(content).toContain('Last Session Type:');
    });

    it('should update Last Session Type', async () => {
      const intelligence = await import('../src/modules/intelligence.js');

      await intelligence.initializeIntelligenceLearning(tempDir);

      intelligence.updateIntelligenceLearning(tempDir, {
        type: 'exit',
        filename: 'exit-2026-04-21T10-30-00.md',
        sessionId: 'session-exit',
        messageCount: 3
      });

      jest.advanceTimersByTime(100);
      await Promise.resolve();

      const content = await fs.readFile(path.join(ctxDir, 'intelligence-learning.md'), 'utf-8');
      expect(content).toContain('Last Session Type:');
    });

    it('should handle invalid session info gracefully', async () => {
      const intelligence = await import('../src/modules/intelligence.js');

      // Initialize first
      await intelligence.initializeIntelligenceLearning(tempDir);

      // Queue update with null sessionInfo - should not throw
      intelligence.updateIntelligenceLearning(tempDir, null);
      jest.advanceTimersByTime(100);
      await Promise.resolve();

      // If we get here without throwing, test passes
      expect(true).toBe(true);
    });

    it('should return promise that resolves when queue completes', async () => {
      const intelligence = await import('../src/modules/intelligence.js');

      await intelligence.initializeIntelligenceLearning(tempDir);

      // Call update - returns a promise that resolves when queue completes
      const resultPromise = intelligence.updateIntelligenceLearning(tempDir, {
        type: 'exit',
        filename: 'exit-test.md',
        sessionId: 'test-123'
      });

      // It should return a promise
      expect(resultPromise).toBeInstanceOf(Promise);

      // Wait for it to complete
      await resultPromise;
    });
  });

  describe('queue-based serialization', () => {
    it('should process updates through queue sequentially', async () => {
      const intelligence = await import('../src/modules/intelligence.js');

      // Initialize
      await intelligence.initializeIntelligenceLearning(tempDir);

      // Queue multiple updates and await each
      await intelligence.updateIntelligenceLearning(tempDir, {
        type: 'compact',
        filename: 'compact-1.md',
        sessionId: 'session-1'
      });

      await intelligence.updateIntelligenceLearning(tempDir, {
        type: 'exit',
        filename: 'exit-2.md',
        sessionId: 'session-2'
      });

      // Both sessions should be recorded
      const content = await fs.readFile(path.join(ctxDir, 'intelligence-learning.md'), 'utf-8');
      expect(content).toContain('session-1');
      expect(content).toContain('session-2');
    });
  });

  describe('fail-safe behavior', () => {
    it('should not throw on errors - fail gracefully', async () => {
      const intelligence = await import('../src/modules/intelligence.js');

      // Don't initialize - try to update directly
      // This should not throw
      expect(() => {
        intelligence.updateIntelligenceLearning('/invalid/path', {
          type: 'compact',
          filename: 'test.md'
        });
      }).not.toThrow();

      jest.advanceTimersByTime(100);
      await Promise.resolve();
    });
  });

  describe('Key Learnings section management', () => {
    it('should add new entries to Key Learnings section', async () => {
      const intelligence = await import('../src/modules/intelligence.js');

      await intelligence.initializeIntelligenceLearning(tempDir);

      intelligence.updateIntelligenceLearning(tempDir, {
        type: 'compact',
        filename: 'compact-entry.md',
        sessionId: 'learning-session',
        messageCount: 10
      });

      jest.advanceTimersByTime(100);
      await Promise.resolve();

      const content = await fs.readFile(path.join(ctxDir, 'intelligence-learning.md'), 'utf-8');
      expect(content).toContain('Key Learnings from Latest Sessions');
    });
  });
});
