/**
 * Intelligence Module Tests
 */

import { jest, describe, it, expect, beforeEach, afterEach } from '@jest/globals';
import fs from 'fs/promises';
import os from 'os';
import path from 'path';

describe('Intelligence Module', () => {
  let tempDir;
  let ctxDir;

  beforeEach(async () => {
    jest.clearAllMocks();
    jest.useFakeTimers();
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'intelligence-test-'));
    ctxDir = path.join(tempDir, '.opencode', 'context-session');
    await fs.mkdir(ctxDir, { recursive: true });
  });

  afterEach(async () => {
    jest.useRealTimers();
    try {
      await fs.rm(tempDir, { recursive: true });
    } catch {}
  });

  describe('initializeIntelligenceLearning(baseDir)', () => {
    it('should create intelligence-learning.md with template content', async () => {
      const intelligence = await import('../src/modules/intelligence.js');

      await intelligence.initializeIntelligenceLearning(tempDir);

      const filePath = path.join(ctxDir, 'intelligence-learning.md');
      const content = await fs.readFile(filePath, 'utf-8');

      expect(content).toContain('Intelligence Learning');
      expect(content).toContain('Last Updated');
      expect(content).toContain('Key Learnings from Latest Sessions');
      expect(content).toContain('Auto-generated by OpenCode Context Plugin');
    });

    it('should skip if file already exists', async () => {
      const intelligence = await import('../src/modules/intelligence.js');

      // Create existing file
      await fs.writeFile(path.join(ctxDir, 'intelligence-learning.md'), '# Existing content\n');

      // Should not overwrite
      await intelligence.initializeIntelligenceLearning(tempDir);

      const content = await fs.readFile(path.join(ctxDir, 'intelligence-learning.md'), 'utf-8');
      expect(content).toBe('# Existing content\n');
    });

    it('should return the file path', async () => {
      const intelligence = await import('../src/modules/intelligence.js');

      const result = await intelligence.initializeIntelligenceLearning(tempDir);

      expect(result).toContain('intelligence-learning.md');
    });
  });

  describe('updateIntelligenceLearning(directory) - Agent Function', () => {
    it('should update intelligence learning file from agent', async () => {
      const agent = await import('../src/agents/generateIntelligenceLearning.js');
      const intelligence = await import('../src/modules/intelligence.js');

      // First initialize
      await intelligence.initializeIntelligenceLearning(tempDir);

      // Create a session file in the hierarchical structure (today's date)
      const today = new Date();
      const year = today.getFullYear();
      const month = String(today.getMonth() + 1).padStart(2, '0');
      const day = String(today.getDate()).padStart(2, '0');
      const weekNum = String(Math.ceil(today.getDate() / 7)).padStart(2, '0');
      const sessionDir = path.join(tempDir, '.opencode', 'context-session', String(year), month, `W${weekNum}`, day);
      await fs.mkdir(sessionDir, { recursive: true });

      const sessionContent = `---
sessionId: "test-123"
title: "Test Session"
---

# Session Context

## Goal
Test the intelligence learning update

## Accomplished
Created test session file

## Discoveries
Testing agent function
`;
      const sessionFile = path.join(sessionDir, 'exit-2026-04-21T10-30-00.md');
      await fs.writeFile(sessionFile, sessionContent);

      // Call agent update function
      const result = await agent.updateIntelligenceLearning(tempDir);

      expect(result.success).toBe(true);
      
      const content = await fs.readFile(path.join(ctxDir, 'intelligence-learning.md'), 'utf-8');
      expect(content).toContain('Intelligence Learning');
      expect(content).toContain('Test Session');
    });

    it('should skip greeting sessions', async () => {
      const agent = await import('../src/agents/generateIntelligenceLearning.js');
      const intelligence = await import('../src/modules/intelligence.js');

      await intelligence.initializeIntelligenceLearning(tempDir);

      // Create a greeting-only session in hierarchical structure
      const today = new Date();
      const year = today.getFullYear();
      const month = String(today.getMonth() + 1).padStart(2, '0');
      const day = String(today.getDate()).padStart(2, '0');
      const weekNum = String(Math.ceil(today.getDate() / 7)).padStart(2, '0');
      const sessionDir = path.join(tempDir, '.opencode', 'context-session', String(year), month, `W${weekNum}`, day);
      await fs.mkdir(sessionDir, { recursive: true });

      const sessionContent = `---
sessionId: "greeting-123"
title: "Light chat greeting: oi"
---

# Session Context

## Messages

### Message 0 [user]

oi
`;
      const sessionFile = path.join(sessionDir, 'compact-2026-04-21T11-00-00.md');
      await fs.writeFile(sessionFile, sessionContent);

      const result = await agent.updateIntelligenceLearning(tempDir);

      expect(result.skipped).toBe(true);
      expect(result.reason).toContain('No new meaningful sessions');
    });
  });
});
