import fs from "fs/promises";
import path from "path";
import { createDebugLogger } from '../../utils/debug.js';
import { atomicWrite } from '../../utils/fileUtils.js';
import { CONTEXT_SESSION_DIR } from '../../config.js';

const logger = createDebugLogger('intelligence:core');

export function isHighPriority(sessionData) {
  if (!sessionData || typeof sessionData !== 'object') return false;
  return sessionData.priority === 'high';
}

export async function initializeIntelligenceLearning(baseDir) {
  if (!baseDir || typeof baseDir !== 'string') {
    throw new Error('initializeIntelligenceLearning: baseDir is required and must be a string');
  }

  const ctxDir = path.join(baseDir, CONTEXT_SESSION_DIR);
  const filePath = path.join(ctxDir, 'intelligence-learning.md');
  
  try {
    try {
      await fs.access(filePath);
      logger(`File already exists, skipping: ${filePath}`);
      return filePath;
    } catch {
    }
    
    const projectName = path.basename(baseDir);
    const timestamp = new Date().toISOString();
    
    const content = `# Intelligence Learning - ${projectName}

**Last Updated:** ${timestamp}

> This file auto-populates as sessions are analyzed. See below for current state.

---

## Current Patterns

### Pinned Patterns
- [Auto-populated from cross-session analysis]

### Recent Sessions
- [Auto-populated from recent sessions]

### Bug Patterns
- [Auto-populated from session analysis]

---

*Auto-generated by OpenCode Context Plugin*
`;
    
    await fs.mkdir(ctxDir, { recursive: true });
    await atomicWrite(filePath, content);
    logger(`Initialized: ${filePath}`);
    return filePath;
  } catch (error) {
    logger(`init failed: ${error.message}`);
    throw error;
  }
}
