import fs from "fs/promises";
import os from "os";
import path from "path";
import { atomicWrite } from './fileUtils.js';
import { createDebugLogger } from './debug.js';

const logger = createDebugLogger('global-intelligence');

/**
 * Get the global intelligence file path
 * @returns {string} Path to ~/.opencode/global-intelligence.md
 */
export function getGlobalIntelligencePath() {
  const homeDir = os.homedir();
  return path.join(homeDir, '.opencode', 'global-intelligence.md');
}

/**
 * Ensure the .opencode directory exists
 */
async function ensureOpencodeDir() {
  const opencodeDir = path.join(os.homedir(), '.opencode');
  await fs.mkdir(opencodeDir, { recursive: true });
  return opencodeDir;
}

/**
 * Initialize the global intelligence file if it doesn't exist
 * @returns {Promise<string>} Path to the global intelligence file
 */
export async function initializeGlobalIntelligence() {
  const filePath = getGlobalIntelligencePath();
  
  // Check if file already exists
  try {
    await fs.access(filePath);
    logger(`[GlobalIntelligence] File already exists: ${filePath}`);
    return filePath;
  } catch {
    // File doesn't exist, proceed with creation
  }
  
  const timestamp = new Date().toISOString();
  
  const content = `# Global Intelligence

## Last Updated
- **Timestamp:** ${timestamp}
- **Projects:** 0
- **Sessions:** 0

## Cross-Project Patterns

### Recurring Themes
- [Auto-populated from cross-project analysis]

### Shared Architectural Decisions
- [Auto-populated from project learnings]

### Common Bug Patterns
- [Auto-populated from project bug databases]

## Bug Database (Universal)

### High-Impact Bugs
- [Bug entries that apply across multiple projects]

### Prevention Strategies
- [Universal bug prevention patterns]

## Template Learnings

### Project Structure Patterns
- [Learnings about project organization]

### Development Workflows
- [Effective workflow patterns]

## Project Directory

### Active Projects
- [List of projects that have contributed learnings]

---

*Auto-generated by OpenCode Context Plugin*
*Aggregates learnings across all projects*
`;

  try {
    await ensureOpencodeDir();
    await atomicWrite(filePath, content);
    logger(`[GlobalIntelligence] Initialized global intelligence file: ${filePath}`);
    console.log(`[context-plugin] Global intelligence file initialized at ${filePath}`);
  } catch (error) {
    logger(`[GlobalIntelligence] Error initializing global intelligence: ${error.message}`);
    // Don't throw - fail gracefully
  }
  
  return filePath;
}

// Queue-based serialization for global intelligence updates
let globalWriteQueue = Promise.resolve();

/**
 * Update the global intelligence file with project learnings
 * Uses queue-based serialization to prevent write conflicts
 * 
 * @param {string} projectName - Name of the project
 * @param {Object} sessionInfo - Session information to append
 * @returns {Promise<void>}
 */
export async function updateGlobalIntelligence(projectName, sessionInfo) {
  if (!projectName) {
    logger(`[GlobalIntelligence] No project name provided, skipping update`);
    return;
  }
  
  globalWriteQueue = globalWriteQueue.then(async () => {
    try {
      const filePath = getGlobalIntelligencePath();
      
      // Ensure file exists
      try {
        await fs.access(filePath);
      } catch {
        // File doesn't exist, initialize it first
        await initializeGlobalIntelligence();
      }
      
      // Read existing content
      let content;
      try {
        content = await fs.readFile(filePath, 'utf-8');
      } catch (error) {
        logger(`[GlobalIntelligence] Cannot read global intelligence file: ${error.message}`);
        return;
      }
      
      const timestamp = sessionInfo?.timestamp || new Date().toISOString();
      const sessionCount = sessionInfo?.sessionCount || 1;
      const sessionType = sessionInfo?.lastSessionType || 'unknown';
      
      // Update Last Updated section
      const lines = content.split('\n');
      const updatedLines = [];
      let inLastUpdatedSection = false;
      let projectsCount = 0;
      let sessionsCount = 0;
      
      for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        
        if (line.startsWith('## Last Updated')) {
          inLastUpdatedSection = true;
          updatedLines.push(line);
          continue;
        }
        
        if (inLastUpdatedSection && line.startsWith('## ')) {
          inLastUpdatedSection = false;
        }
        
        // Update timestamp
        if (inLastUpdatedSection && line.includes('**Timestamp:**')) {
          updatedLines.push(`- **Timestamp:** ${timestamp}`);
          continue;
        }
        
        // Update projects count
        if (inLastUpdatedSection && line.includes('**Projects:**')) {
          // Count existing project entries first
          const projectEntries = content.match(/### [A-Za-z]/g);
          projectsCount = projectEntries ? projectEntries.length : 0;
          updatedLines.push(`- **Projects:** ${projectsCount + 1}`);
          continue;
        }
        
        // Update sessions count
        if (inLastUpdatedSection && line.includes('**Sessions:**')) {
          const match = line.match(/Sessions:\s*(\d+)/);
          sessionsCount = match ? parseInt(match[1], 10) + sessionCount : sessionCount;
          updatedLines.push(`- **Sessions:** ${sessionsCount}`);
          continue;
        }
        
        updatedLines.push(line);
      }
      
      content = updatedLines.join('\n');
      
      // Find Project Directory section
      const projectDirMarker = '### Active Projects';
      const projectDirIndex = content.indexOf(projectDirMarker);
      
      if (projectDirIndex !== -1) {
        // Check if this project already exists
        const projectEntryMarker = `### ${projectName}`;
        const existingProjectIndex = content.indexOf(projectEntryMarker);
        
        if (existingProjectIndex !== -1) {
          // Update existing project entry
          // Find the next ### or end of file
          let entryEnd = content.indexOf('\n### ', existingProjectIndex + 1);
          if (entryEnd === -1) entryEnd = content.indexOf('\n---', existingProjectIndex);
          if (entryEnd === -1) entryEnd = content.length;
          
          const oldEntry = content.slice(existingProjectIndex, entryEnd);
          
          // Build updated entry
          const newEntry = `${projectEntryMarker}\n- **Last Updated:** ${timestamp}\n- **Session Count:** ${sessionCount}\n- **Last Session Type:** ${sessionType}`;
          
          content = content.replace(oldEntry, newEntry);
          logger(`[GlobalIntelligence] Updated existing project entry: ${projectName}`);
        } else {
          // Add new project entry
          const sectionStart = projectDirIndex + projectDirMarker.length;
          const insertPos = content.indexOf('\n\n', sectionStart);
          const actualInsertPos = insertPos !== -1 ? insertPos + 2 : content.length;
          
          const newEntry = `\n### ${projectName}\n- **Last Updated:** ${timestamp}\n- **Session Count:** ${sessionCount}\n- **Last Session Type:** ${sessionType}`;
          
          content = content.slice(0, actualInsertPos) + newEntry + content.slice(actualInsertPos);
          logger(`[GlobalIntelligence] Added new project entry: ${projectName}`);
        }
      }
      
      // Atomic write
      await atomicWrite(filePath, content);
      logger(`[GlobalIntelligence] Updated global intelligence file`);
    } catch (error) {
      logger(`[GlobalIntelligence] Error updating global intelligence: ${error.message}`);
      // Don't throw - fail gracefully to not affect local operations
    }
  });
  
  await globalWriteQueue;
}

/**
 * Query the global intelligence file for patterns
 * 
 * @param {string} pattern - Search pattern
 * @returns {Promise<Object[]>} Array of matching entries
 */
export async function queryGlobalIntelligence(pattern) {
  if (!pattern) {
    return [];
  }
  
  const filePath = getGlobalIntelligencePath();
  
  try {
    const content = await fs.readFile(filePath, 'utf-8');
    
    const results = [];
    const lowerPattern = pattern.toLowerCase();
    const lines = content.split('\n');
    
    let currentSection = '';
    let currentEntry = '';
    
    for (const line of lines) {
      if (line.startsWith('### ')) {
        // Save previous entry if it matches
        if (currentEntry.toLowerCase().includes(lowerPattern)) {
          results.push({
            section: currentSection,
            content: currentEntry.trim()
          });
        }
        currentSection = line.replace('### ', '');
        currentEntry = '';
      } else if (line.startsWith('## ')) {
        // Save previous entry if it matches
        if (currentEntry.toLowerCase().includes(lowerPattern)) {
          results.push({
            section: currentSection,
            content: currentEntry.trim()
          });
        }
        currentSection = '';
        currentEntry = '';
      }
      
      currentEntry += line + '\n';
    }
    
    // Check last entry
    if (currentEntry.toLowerCase().includes(lowerPattern)) {
      results.push({
        section: currentSection,
        content: currentEntry.trim()
      });
    }
    
    return results;
  } catch (error) {
    logger(`[GlobalIntelligence] Error querying global intelligence: ${error.message}`);
    return [];
  }
}