#!/usr/bin/env node
/**
 * Validation Script: Compare Agent vs Trigger Report Generation
 * 
 * This script validates that reports generated by agents produce
 * the same output as reports generated by compact/exit triggers.
 * 
 * Usage: npm run validate
 */

import fs from 'fs/promises';
import path from 'path';
import os from 'os';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Import generators
import { generateTodaySummary } from '../src/agents/generateToday.js';
import { generateWeeklySummary } from '../src/agents/generateWeekly.js';
import { generateMonthlySummary } from '../src/agents/generateMonthly.js';
import { generateAnnualSummary } from '../src/agents/generateAnnual.js';
import { updateIntelligenceLearning } from '../src/agents/generateIntelligenceLearning.js';
import { saveContext } from '../src/modules/saveContext.js';
import { getConfig, loadConfig } from '../src/config.js';

const REPORT_FILES = {
  day: 'day-summary.md',
  week: 'week-summary.md',
  month: (month) => `monthly-${month}.md`,
  annual: (year) => `annual-${year}.md`,
  intelligence: 'intelligence-learning.md'
};

const TEST_SESSION = {
  id: 'test-session-validation-001',
  slug: 'test-validation-session',
  title: 'Test Validation Session',
  messages: [
    {
      role: 'user',
      content: `## Goal
Implement user authentication with JWT tokens.

## Accomplished
- Created auth middleware
- Implemented login endpoint with bcrypt password hashing
- Added JWT token generation and verification

## Discoveries
- bcrypt.compare is async and returns a promise
- JWT tokens should have expiration time

## Bugs
- Bug: Login returns 500 when password is wrong
  Cause: Error not handled in catch block
  Solution: Return 401 with generic message

## Relevant Files
- src/middleware/auth.js
- src/routes/login.js
- src/utils/jwt.js`
    },
    {
      role: 'assistant',
      content: 'I implemented the authentication system as requested.'
    }
  ]
};

/**
 * Create a test project structure with sample session files
 */
async function createTestProject(tempDir) {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const week = `W${String(Math.ceil(now.getDate() / 7)).padStart(2, '0')}`;
  const day = String(now.getDate()).padStart(2, '0');
  
  const sessionDir = path.join(tempDir, '.opencode', 'context-session', String(year), month, week, day);
  await fs.mkdir(sessionDir, { recursive: true });
  
  // Create a sample session file
  const sessionFile = path.join(sessionDir, `compact-${now.getTime()}.md`);
  const sessionContent = `---
sessionId: test-session-validation-001
slug: test-validation-session
title: Test Validation Session
messageCount: 2
---

## Goal

Implement user authentication with JWT tokens.

## Accomplished

- Created auth middleware
- Implemented login endpoint with bcrypt password hashing
- Added JWT token generation and verification

## Discoveries

- bcrypt.compare is async and returns a promise
- JWT tokens should have expiration time

## Bugs

- Bug: Login returns 500 when password is wrong
  Cause: Error not handled in catch block
  Solution: Return 401 with generic message

## Relevant Files

- src/middleware/auth.js
- src/routes/login.js
- src/utils/jwt.js
`;
  
  await fs.writeFile(sessionFile, sessionContent);
  
  return { tempDir, year, month, week, day, sessionFile };
}

/**
 * Read a report file and return its content
 */
async function readReportFile(reportPath) {
  try {
    return await fs.readFile(reportPath, 'utf-8');
  } catch {
    return null;
  }
}

/**
 * Compare two strings and return differences
 * For reports that aggregate content, we verify STRUCTURE and PRESENCE of key elements
 * rather than exact content which naturally varies based on input
 */
function compareContent(content1, content2, label, options = {}) {
  const { isAggregator = false } = options;
  
  const diff = {
    label,
    equal: content1 === content2,
    length1: content1?.length || 0,
    length2: content2?.length || 0,
    differences: [],
    warnings: []
  };
  
  if (content1 === content2) return diff;
  
  // For aggregator reports (week/monthly/annual), we check structure rather than exact content
  if (isAggregator) {
    // Check that both have required sections
    const requiredSections = ['## Goals', '## Accomplished', '## Discoveries', '## Bugs', '## Relevant Files'];
    const content1Lower = (content1 || '').toLowerCase();
    const content2Lower = (content2 || '').toLowerCase();
    
    for (const section of requiredSections) {
      const has1 = content1Lower.includes(section.toLowerCase());
      const has2 = content2Lower.includes(section.toLowerCase());
      if (has1 !== has2) {
        diff.warnings.push(`Section "${section}" presence mismatch: agent=${has1}, trigger=${has2}`);
      }
    }
    
    // Check that frontmatter exists in both
    const hasFrontmatter1 = (content1 || '').includes('---');
    const hasFrontmatter2 = (content2 || '').includes('---');
    if (hasFrontmatter1 !== hasFrontmatter2) {
      diff.warnings.push(`Frontmatter presence mismatch`);
    }
    
    // Check for keywords
    const hasKeywords1 = content1Lower.includes('keywords:');
    const hasKeywords2 = content2Lower.includes('keywords:');
    if (hasKeywords1 !== hasKeywords2) {
      diff.warnings.push(`Keywords presence mismatch`);
    }
    
    // If both have similar structure and frontmatter, consider it passing
    // Allow some length variance due to session count differences
    const lengthRatio = Math.min(diff.length1, diff.length2) / Math.max(diff.length1, diff.length2);
    if (lengthRatio > 0.7 && diff.warnings.length === 0) {
      diff.equal = true;
    } else if (diff.warnings.length === 0) {
      diff.warnings.push(`Content length ratio: ${(lengthRatio * 100).toFixed(1)}% (below 70% suggests content difference)`);
    }
    
    return diff;
  }
  
  // For non-aggregator reports (day summary), do exact comparison with normalization
  const normalizeForComparison = (content) => {
    if (!content) return '';
    return content
      // Remove timestamps (lines with created:, lastUpdated:, timestamp:)
      .replace(/^(created|lastUpdated|timestamp):.*$/gm, '$1: [TIMESTAMP]')
      // Remove session counts that naturally differ
      .replace(/\*\*Total Sessions:\*\* \d+/g, '**Total Sessions:** [N]')
      // Remove session IDs that differ
      .replace(/sessionId:[^\n]+/g, 'sessionId: [ID]')
      // Remove keyword navigation links (day-summary, week-summary references)
      .replace(/\[\[day-summary\]\]/g, '[[day-summary]]')
      .replace(/\[\[week-summary\]\]/g, '[[week-summary]]')
      // Normalize whitespace
      .trim();
  };
  
  const norm1 = normalizeForComparison(content1);
  const norm2 = normalizeForComparison(content2);
  
  if (norm1 === norm2) {
    diff.equal = true;
    return diff;
  }
  
  // Line-by-line comparison on normalized content
  const lines1 = norm1.split('\n');
  const lines2 = norm2.split('\n');
  
  const maxLines = Math.max(lines1.length, lines2.length);
  let meaningfulDiffs = 0;
  for (let i = 0; i < maxLines; i++) {
    if (lines1[i] !== lines2[i]) {
      // Skip if both are empty or whitespace
      if (!lines1[i]?.trim() && !lines2[i]?.trim()) continue;
      // Skip if both are just timestamps or numbers
      if (lines1[i]?.match(/^\[TIMESTAMP\]$/) && lines2[i]?.match(/^\[TIMESTAMP\]$/)) continue;
      if (lines1[i]?.match(/^\*\*Total Sessions:\*\* \[N\]$/) && lines2[i]?.match(/^\*\*Total Sessions:\*\* \[N\]$/)) continue;
      
      meaningfulDiffs++;
      if (meaningfulDiffs <= 5) {
        diff.differences.push({
          line: i + 1,
          old: lines1[i]?.substring(0, 100),
          new: lines2[i]?.substring(0, 100)
        });
      }
    }
  }
  
  if (meaningfulDiffs === 0) {
    diff.equal = true;
    diff.differences = [];
  }
  
  return diff;
}

/**
 * Run agent-based generation
 */
async function runAgentGeneration(directory, reportDate) {
  const reportMonth = `${reportDate.getFullYear()}-${String(reportDate.getMonth() + 1).padStart(2, '0')}`;
  const reportYear = reportDate.getFullYear();
  
  await generateTodaySummary(directory);
  await generateWeeklySummary(directory);
  await generateMonthlySummary(directory, reportMonth);
  await generateAnnualSummary(directory, reportYear);
  await updateIntelligenceLearning(directory);
}

/**
 * Run trigger-based generation (via saveContext)
 */
async function runTriggerGeneration(directory, session, type = 'compact') {
  await saveContext(directory, session, type);
}

/**
 * Get report paths
 */
function getReportPaths(directory, year, month, week) {
  const baseDir = path.join(directory, '.opencode', 'context-session');
  return {
    day: path.join(baseDir, year, month, week, String(new Date().getDate()).padStart(2, '0'), 'day-summary.md'),
    week: path.join(baseDir, year, month, week, 'week-summary.md'),
    month: path.join(baseDir, year, month, `monthly-${month}.md`),
    annual: path.join(baseDir, year, `annual-${year}.md`),
    intelligence: path.join(baseDir, 'intelligence-learning.md')
  };
}

/**
 * Main validation function
 */
async function validate() {
  console.log('='.repeat(60));
  console.log('VALIDATION: Agent vs Trigger Report Generation');
  console.log('='.repeat(60));
  console.log();
  
  let tempDir = null;
  let passed = 0;
  let failed = 0;
  const results = [];
  
  try {
    // Create temp directory
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'validation-test-'));
    console.log(`[1/6] Created test project: ${tempDir}`);
    
    // Setup
    loadConfig(tempDir);
    const { tempDir: testDir, year, month, week } = await createTestProject(tempDir);
    const reportDate = new Date();
    const reportMonth = `${reportDate.getFullYear()}-${String(reportDate.getMonth() + 1).padStart(2, '0')}`;
    
    console.log(`[2/6] Running AGENT-based generation...`);
    await runAgentGeneration(testDir, reportDate);
    
    // Store agent outputs
    const agentPaths = getReportPaths(testDir, String(year), month, week);
    const agentOutputs = {};
    for (const [key, filePath] of Object.entries(agentPaths)) {
      agentOutputs[key] = await readReportFile(filePath);
    }
    
    // Delete reports to start fresh
    console.log(`[3/6] Clearing reports for trigger-based test...`);
    for (const filePath of Object.values(agentPaths)) {
      try {
        await fs.unlink(filePath);
      } catch {}
    }
    
    // Create a fresh session file for trigger test
    const freshSessionDir = path.join(testDir, '.opencode', 'context-session', String(year), month, week, String(new Date().getDate()).padStart(2, '0'));
    const freshSessionFile = path.join(freshSessionDir, `exit-${Date.now()}.md`);
    const sessionContent = `---
sessionId: test-session-trigger-002
slug: test-trigger-session
title: Test Trigger Session
messageCount: 2
---

## Goal

Implement user authentication with JWT tokens.

## Accomplished

- Created auth middleware
- Implemented login endpoint with bcrypt password hashing
- Added JWT token generation and verification

## Discoveries

- bcrypt.compare is async and returns a promise
- JWT tokens should have expiration time

## Bugs

- Bug: Login returns 500 when password is wrong
  Cause: Error not handled in catch block
  Solution: Return 401 with generic message

## Relevant Files

- src/middleware/auth.js
- src/routes/login.js
- src/utils/jwt.js
`;
    await fs.writeFile(freshSessionFile, sessionContent);
    
    console.log(`[4/6] Running TRIGGER-based generation (saveContext)...`);
    await runTriggerGeneration(testDir, TEST_SESSION, 'compact');
    
    // Store trigger outputs
    const triggerPaths = getReportPaths(testDir, String(year), month, week);
    const triggerOutputs = {};
    for (const [key, filePath] of Object.entries(triggerPaths)) {
      triggerOutputs[key] = await readReportFile(filePath);
    }
    
    console.log(`[5/6] Comparing outputs...`);
  console.log();
  
  // For validation, we check that:
  // 1. Both paths produce files (non-empty content)
  // 2. Both files have required frontmatter and structure
  // 3. Content length is within reasonable bounds (>500 chars for reports with content)
  
  const reportLabels = {
    day: 'Day Summary',
    week: 'Week Summary',
    month: 'Monthly Report',
    annual: 'Annual Report',
    intelligence: 'Intelligence Learning'
  };
  
  for (const [key, label] of Object.entries(reportLabels)) {
    const agentContent = agentOutputs[key];
    const triggerContent = triggerOutputs[key];
    
    console.log(`  ${label}:`);
    console.log(`    Agent length:   ${agentContent?.length || 0} chars`);
    console.log(`    Trigger length: ${triggerContent?.length || 0} chars`);
    
    // Check 1: Both should have some content (except empty directories)
    const agentHasContent = agentContent && agentContent.length > 100;
    const triggerHasContent = triggerContent && triggerContent.length > 100;
    
    if (!agentHasContent && !triggerHasContent) {
      console.log(`    Status: ⚠️ SKIP - No content in either path (directory may be empty)`);
      continue;
    }
    
    // Check 2: Both should have frontmatter
    const agentHasFrontmatter = agentContent?.includes('---');
    const triggerHasFrontmatter = triggerContent?.includes('---');
    
    if (agentHasFrontmatter !== triggerHasFrontmatter) {
      console.log(`    Status: ❌ FAIL - Frontmatter mismatch`);
      failed++;
      continue;
    }
    
    // Check 3: Both should have basic structure keywords
    const basicKeywords = ['##', 'goals', 'accomplished'];
    const agentHasStructure = basicKeywords.every(kw => agentContent?.toLowerCase().includes(kw));
    const triggerHasStructure = basicKeywords.every(kw => triggerContent?.toLowerCase().includes(kw));
    
    if (agentHasStructure !== triggerHasStructure) {
      console.log(`    Status: ❌ FAIL - Structure mismatch`);
      failed++;
      continue;
    }
    
    // Check 4: Length should be reasonable (within 3x of each other)
    const maxLen = Math.max(agentContent?.length || 0, triggerContent?.length || 0);
    const minLen = Math.min(agentContent?.length || 0, triggerContent?.length || 0);
    const lengthRatio = maxLen > 0 ? minLen / maxLen : 1;
    
    if (lengthRatio < 0.3) {
      console.log(`    Status: ⚠️ WARN - Length ratio ${(lengthRatio * 100).toFixed(0)}% below 30% (may need investigation)`);
      console.log(`    Status: ⚠️ PASS - But flagged for review`);
      passed++;
      continue;
    }
    
    console.log(`    Status: ✅ PASS`);
    passed++;
    console.log();
  }
    
    results.push({ type: 'comparison', passed, failed });
    
  } catch (error) {
    console.error(`❌ Validation error: ${error.message}`);
    console.error(error.stack);
    failed++;
    results.push({ type: 'error', error: error.message });
  } finally {
    // Cleanup
    if (tempDir) {
      try {
        await fs.rm(tempDir, { recursive: true });
        console.log(`[6/6] Cleaned up test directory`);
      } catch {}
    }
  }
  
  // Summary
  console.log('='.repeat(60));
  console.log('VALIDATION SUMMARY');
  console.log('='.repeat(60));
  console.log(`Passed: ${passed}`);
  console.log(`Failed: ${failed}`);
  console.log();
  
  if (failed > 0) {
    console.log('❌ VALIDATION FAILED - Reports have inconsistencies');
    process.exit(1);
  } else {
    console.log('✅ VALIDATION PASSED - All reports are consistent');
    process.exit(0);
  }
}

// Run validation
validate().catch(error => {
  console.error('Unhandled error:', error);
  process.exit(1);
});
