#!/usr/bin/env node
/**
 * Validation Script: Compare Agent vs Trigger Report Generation
 * 
 * This script validates that reports generated by agents produce
 * the same output as reports generated by compact/exit triggers.
 * 
 * Usage: npm run validate
 */

import fs from 'fs/promises';
import path from 'path';
import os from 'os';
import { fileURLToPath } from 'url';
import { getWeek } from 'date-fns';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Import generators
import { generateTodaySummary } from '../src/agents/generateToday.js';
import { generateWeeklySummary } from '../src/agents/generateWeekly.js';
import { generateMonthlySummary } from '../src/agents/generateMonthly.js';
import { generateAnnualSummary } from '../src/agents/generateAnnual.js';
import { updateIntelligenceLearning } from '../src/agents/generateIntelligenceLearning.js';
import { saveContext } from '../src/modules/saveContext.js';
import { getConfig, loadConfig } from '../src/config.js';

const REPORT_FILES = {
  day: 'day-summary.md',
  week: 'week-summary.md',
  month: (month) => `monthly-${month}.md`,
  annual: (year) => `annual-${year}.md`,
  intelligence: 'intelligence-learning.md'
};

const TEST_SESSION = {
  id: 'test-session-validation-001',
  slug: 'test-validation-session',
  title: 'Test Validation Session',
  messages: [
    {
      role: 'user',
      content: `## Goal
Implement user authentication with JWT tokens.

## Accomplished
- Created auth middleware
- Implemented login endpoint with bcrypt password hashing
- Added JWT token generation and verification

## Discoveries
- bcrypt.compare is async and returns a promise
- JWT tokens should have expiration time

## Bugs
- Bug: Login returns 500 when password is wrong
  Cause: Error not handled in catch block
  Solution: Return 401 with generic message

## Relevant Files
- src/middleware/auth.js
- src/routes/login.js
- src/utils/jwt.js`
    },
    {
      role: 'assistant',
      content: 'I implemented the authentication system as requested.'
    }
  ]
};

/**
 * Create a test project structure with sample session files
 */
async function createTestProject(tempDir) {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const week = `W${String(Math.ceil(now.getDate() / 7)).padStart(2, '0')}`;
  const day = String(now.getDate()).padStart(2, '0');
  
  const sessionDir = path.join(tempDir, '.opencode', 'context-session', String(year), month, week, day);
  await fs.mkdir(sessionDir, { recursive: true });
  
  // Create a sample session file
  const sessionFile = path.join(sessionDir, `compact-${now.getTime()}.md`);
  const sessionContent = `---
sessionId: test-session-validation-001
slug: test-validation-session
title: Test Validation Session
messageCount: 2
---

## Goal

Implement user authentication with JWT tokens.

## Accomplished

- Created auth middleware
- Implemented login endpoint with bcrypt password hashing
- Added JWT token generation and verification

## Discoveries

- bcrypt.compare is async and returns a promise
- JWT tokens should have expiration time

## Bugs

- Bug: Login returns 500 when password is wrong
  Cause: Error not handled in catch block
  Solution: Return 401 with generic message

## Relevant Files

- src/middleware/auth.js
- src/routes/login.js
- src/utils/jwt.js
`;
  
  await fs.writeFile(sessionFile, sessionContent);
  
  return { tempDir, year, month, week, day, sessionFile };
}

/**
 * Read a report file and return its content
 */
async function readReportFile(reportPath) {
  try {
    return await fs.readFile(reportPath, 'utf-8');
  } catch {
    return null;
  }
}

/**
 * Compare two strings and return differences
 * For reports that aggregate content, we verify STRUCTURE and PRESENCE of key elements
 * rather than exact content which naturally varies based on input
 */
function compareContent(content1, content2, label, options = {}) {
  const { isAggregator = false } = options;
  
  const diff = {
    label,
    equal: content1 === content2,
    length1: content1?.length || 0,
    length2: content2?.length || 0,
    differences: [],
    warnings: []
  };
  
  if (content1 === content2) return diff;
  
  // For aggregator reports (week/monthly/annual), we check structure rather than exact content
  if (isAggregator) {
    // Check that both have required sections
    const requiredSections = ['## Goals', '## Accomplished', '## Discoveries', '## Bugs', '## Relevant Files'];
    const content1Lower = (content1 || '').toLowerCase();
    const content2Lower = (content2 || '').toLowerCase();
    
    for (const section of requiredSections) {
      const has1 = content1Lower.includes(section.toLowerCase());
      const has2 = content2Lower.includes(section.toLowerCase());
      if (has1 !== has2) {
        diff.warnings.push(`Section "${section}" presence mismatch: agent=${has1}, trigger=${has2}`);
      }
    }
    
    // Check that frontmatter exists in both
    const hasFrontmatter1 = (content1 || '').includes('---');
    const hasFrontmatter2 = (content2 || '').includes('---');
    if (hasFrontmatter1 !== hasFrontmatter2) {
      diff.warnings.push(`Frontmatter presence mismatch`);
    }
    
    // Check for keywords
    const hasKeywords1 = content1Lower.includes('keywords:');
    const hasKeywords2 = content2Lower.includes('keywords:');
    if (hasKeywords1 !== hasKeywords2) {
      diff.warnings.push(`Keywords presence mismatch`);
    }
    
    // If both have similar structure and frontmatter, consider it passing
    // Allow some length variance due to session count differences
    const lengthRatio = Math.min(diff.length1, diff.length2) / Math.max(diff.length1, diff.length2);
    if (lengthRatio > 0.7 && diff.warnings.length === 0) {
      diff.equal = true;
    } else if (diff.warnings.length === 0) {
      diff.warnings.push(`Content length ratio: ${(lengthRatio * 100).toFixed(1)}% (below 70% suggests content difference)`);
    }
    
    return diff;
  }
  
  // For non-aggregator reports (day summary), do exact comparison with normalization
  const normalizeForComparison = (content) => {
    if (!content) return '';
    return content
      // Remove timestamps (lines with created:, lastUpdated:, timestamp:)
      .replace(/^(created|lastUpdated|timestamp):.*$/gm, '$1: [TIMESTAMP]')
      // Remove session counts that naturally differ
      .replace(/\*\*Total Sessions:\*\* \d+/g, '**Total Sessions:** [N]')
      // Remove session IDs that differ
      .replace(/sessionId:[^\n]+/g, 'sessionId: [ID]')
      // Remove keyword navigation links (day-summary, week-summary references)
      .replace(/\[\[day-summary\]\]/g, '[[day-summary]]')
      .replace(/\[\[week-summary\]\]/g, '[[week-summary]]')
      // Normalize whitespace
      .trim();
  };
  
  const norm1 = normalizeForComparison(content1);
  const norm2 = normalizeForComparison(content2);
  
  if (norm1 === norm2) {
    diff.equal = true;
    return diff;
  }
  
  // Line-by-line comparison on normalized content
  const lines1 = norm1.split('\n');
  const lines2 = norm2.split('\n');
  
  const maxLines = Math.max(lines1.length, lines2.length);
  let meaningfulDiffs = 0;
  for (let i = 0; i < maxLines; i++) {
    if (lines1[i] !== lines2[i]) {
      // Skip if both are empty or whitespace
      if (!lines1[i]?.trim() && !lines2[i]?.trim()) continue;
      // Skip if both are just timestamps or numbers
      if (lines1[i]?.match(/^\[TIMESTAMP\]$/) && lines2[i]?.match(/^\[TIMESTAMP\]$/)) continue;
      if (lines1[i]?.match(/^\*\*Total Sessions:\*\* \[N\]$/) && lines2[i]?.match(/^\*\*Total Sessions:\*\* \[N\]$/)) continue;
      
      meaningfulDiffs++;
      if (meaningfulDiffs <= 5) {
        diff.differences.push({
          line: i + 1,
          old: lines1[i]?.substring(0, 100),
          new: lines2[i]?.substring(0, 100)
        });
      }
    }
  }
  
  if (meaningfulDiffs === 0) {
    diff.equal = true;
    diff.differences = [];
  }
  
  return diff;
}

/**
 * Run agent-based generation
 */
async function runAgentGeneration(directory, reportDate) {
  const reportMonth = `${reportDate.getFullYear()}-${String(reportDate.getMonth() + 1).padStart(2, '0')}`;
  const reportYear = reportDate.getFullYear();
  
  await generateTodaySummary(directory);
  await generateWeeklySummary(directory);
  await generateMonthlySummary(directory, reportMonth);
  await generateAnnualSummary(directory, reportYear);
  await updateIntelligenceLearning(directory);
}

/**
 * Run trigger-based generation (via saveContext)
 */
async function runTriggerGeneration(directory, session, type = 'compact') {
  await saveContext(directory, session, type);
}

/**
 * Get report paths
 * Note: Reports use TWO different paths:
 * - generateTodaySummary -> .opencode/context-session/daily-summary.md (root)
 * - updateDaySummary -> .opencode/context-session/YYYY/MM/WW/DD/day-summary.md (hierarchical)
 */
function getReportPaths(directory, year, month, week) {
  const baseDir = path.join(directory, '.opencode', 'context-session');
  return {
    // Root path (used by generateTodaySummary/generateToday agent)
    day: path.join(baseDir, 'daily-summary.md'),
    // Root path for agent-based week (no date in path)
    weekRoot: path.join(baseDir, 'week-summary.md'),
    // Hierarchical paths (used by updateDaySummary/updateWeekSummary and saveContext trigger)
    dayHierarchical: path.join(baseDir, year, month, week, String(new Date().getDate()).padStart(2, '0'), 'day-summary.md'),
    week: path.join(baseDir, year, month, week, 'week-summary.md'),
    month: path.join(baseDir, year, month, `monthly-${month}.md`),
    annual: path.join(baseDir, year, `annual-${year}.md`),
    intelligence: path.join(baseDir, 'intelligence-learning.md')
  };
}

/**
 * Main validation function
 */
async function validate() {
  console.log('='.repeat(60));
  console.log('VALIDATION: Agent vs Trigger Report Generation');
  console.log('='.repeat(60));
  console.log();
  
  let tempDir = null;
  let passed = 0;
  let failed = 0;
  const results = [];
  
  // Determine the directory to validate - use project root, not temp
  const projectDir = process.cwd();
  const now = new Date();
  const year = String(now.getFullYear());
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const week = `W${String(getWeek(now, { weekStartsOn: 1, firstWeekContainsDate: 4 })).padStart(2, '0')}`;
  const day = String(now.getDate()).padStart(2, '0');
  
  console.log(`Validating project: ${projectDir}`);
  console.log(`Date: ${year}-${month}-${week}-${day}`);
  console.log();
  
  try {
    // Load config for the project
    loadConfig(projectDir);
    
    // Step 1: Run agent-based generation
    console.log(`[1/5] Running AGENT-based generation in project...`);
    const reportDate = now;
    const reportMonth = `${reportDate.getFullYear()}-${String(reportDate.getMonth() + 1).padStart(2, '0')}`;
    const reportYear = reportDate.getFullYear();
    
    await generateTodaySummary(projectDir);
    await generateWeeklySummary(projectDir);
    await generateMonthlySummary(projectDir, reportMonth);
    await generateAnnualSummary(projectDir, reportYear);
    await updateIntelligenceLearning(projectDir);
    
    // Store agent outputs (from the paths agents use)
    const agentPaths = getReportPaths(projectDir, year, month, week);
    const agentOutputs = {
      day: await readReportFile(agentPaths.day),
      dayHierarchical: await readReportFile(agentPaths.dayHierarchical),
      week: await readReportFile(agentPaths.week),
      weekRoot: await readReportFile(agentPaths.weekRoot),
      month: await readReportFile(agentPaths.month),
      annual: await readReportFile(agentPaths.annual),
      intelligence: await readReportFile(agentPaths.intelligence)
    };
    
    console.log(`[2/5] Agent outputs collected`);
    for (const [key, content] of Object.entries(agentOutputs)) {
      console.log(`  ${key}: ${content?.length || 0} chars`);
    }
    console.log();
    
    // Step 3: Store the agent-generated content for later comparison
    const agentSnapshot = { ...agentOutputs };
    
    console.log(`[3/5] Running TRIGGER-based generation (compact/exit saveContext)...`);
    
    // Create a test session file to trigger regeneration
    const sessionDir = path.join(projectDir, '.opencode', 'context-session', year, month, week, day);
    await fs.mkdir(sessionDir, { recursive: true });
    
    const testSession = {
      id: `validation-test-${now.getTime()}`,
      slug: 'validation-test',
      title: 'Validation Test Session',
      messages: [
        {
          role: 'user',
          content: `## Goal
Validation test session for comparing agent vs trigger paths.

## Accomplished
- Ran agent-based generation
- Ran trigger-based generation

## Discoveries
- Both paths should produce consistent reports
- Key difference is in path structure (root vs hierarchical)`
        }
      ]
    };
    
    await saveContext(projectDir, testSession, 'compact');
    
    // Store trigger outputs
    const triggerOutputs = {
      day: await readReportFile(agentPaths.day),
      dayHierarchical: await readReportFile(agentPaths.dayHierarchical),
      week: await readReportFile(agentPaths.week),
      weekRoot: await readReportFile(agentPaths.weekRoot),
      month: await readReportFile(agentPaths.month),
      annual: await readReportFile(agentPaths.annual),
      intelligence: await readReportFile(agentPaths.intelligence)
    };
    
    console.log(`[4/5] Trigger outputs collected`);
    for (const [key, content] of Object.entries(triggerOutputs)) {
      console.log(`  ${key}: ${content?.length || 0} chars`);
    }
    console.log();
    
    console.log(`[5/5] Comparing outputs...`);
    console.log();
    
    // Compare each report type
    const reportLabels = {
      day: 'Day Summary (root)',
      dayHierarchical: 'Day Summary (hierarchical)',
      week: 'Week Summary (hierarchical)',
      weekRoot: 'Week Summary (root)',
      month: 'Monthly Report',
      annual: 'Annual Report',
      intelligence: 'Intelligence Learning'
    };
    
    for (const [key, label] of Object.entries(reportLabels)) {
      const agentContent = agentSnapshot[key];
      const triggerContent = triggerOutputs[key];
      
      console.log(`  ${label}:`);
      console.log(`    Agent length:   ${agentContent?.length || 0} chars`);
      console.log(`    Trigger length: ${triggerContent?.length || 0} chars`);
      
      // Both should have some content
      const agentHasContent = agentContent && agentContent.length > 100;
      const triggerHasContent = triggerContent && triggerContent.length > 100;
      
      if (!agentHasContent && !triggerHasContent) {
        console.log(`    Status: ⚠️ SKIP - No content in either path`);
        continue;
      }
      
      // Both should have frontmatter
      const agentHasFrontmatter = agentContent?.includes('---');
      const triggerHasFrontmatter = triggerContent?.includes('---');
      
      if (agentHasFrontmatter !== triggerHasFrontmatter) {
        console.log(`    Status: ❌ FAIL - Frontmatter mismatch`);
        failed++;
        continue;
      }
      
      // Content length should be similar (within 50%)
      const maxLen = Math.max(agentContent?.length || 0, triggerContent?.length || 0);
      const minLen = Math.min(agentContent?.length || 0, triggerContent?.length || 0);
      const lengthRatio = maxLen > 0 ? minLen / maxLen : 1;
      
      if (lengthRatio < 0.5) {
        console.log(`    Status: ⚠️ WARN - Length ratio ${(lengthRatio * 100).toFixed(0)}% (below 50%)`);
      }
      
      console.log(`    Status: ✅ PASS`);
      passed++;
      console.log();
    }
    
    results.push({ type: 'comparison', passed, failed });
    
  } catch (error) {
    console.error(`❌ Validation error: ${error.message}`);
    console.error(error.stack);
    failed++;
    results.push({ type: 'error', error: error.message });
  }
  
  // Summary
  console.log('='.repeat(60));
  console.log('VALIDATION SUMMARY');
  console.log('='.repeat(60));
  console.log(`Passed: ${passed}`);
  console.log(`Failed: ${failed}`);
  console.log();
  
  if (failed > 0) {
    console.log('❌ VALIDATION FAILED - Reports have inconsistencies');
    process.exit(1);
  } else {
    console.log('✅ VALIDATION PASSED - All reports are consistent');
    process.exit(0);
  }
}

// Run validation
validate().catch(error => {
  console.error('Unhandled error:', error);
  process.exit(1);
});
